Transform the BSD-style Makefile into Debian-style
--- a/Makefile	2020-11-28 12:48:58.558168578 +0100
+++ b/Makefile	2020-11-28 12:48:58.558168578 +0100
@@ -23,10 +23,10 @@
 #OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 #OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PREFIX?=/usr/local
-INSTALLBIN=$(PREFIX)/bin
-INSTALLSHARE=$(PREFIX)/share/games
-INSTALLMAN=$(PREFIX)/share/man
+DESTDIR?=/usr/local
+INSTALLBIN=$(DESTDIR)/bin
+INSTALLSHARE=$(DESTDIR)/share/games
+INSTALLMAN=$(DESTDIR)/share/man
 
 CC?=gcc
 AR?=ar
@@ -75,7 +75,7 @@
 OBJ_TOPLEVEL=${SOURCES_TOPLEVEL:.c=.o}
 
 all:	dMagnetic
-#	strip dMagnetic
+#	#strip dMagnetic
 
 clean:
 	rm -rf dMagnetic
@@ -94,8 +94,8 @@
 	cp dMagnetic $(INSTALLBIN)
 	cp dMagnetic.1 $(INSTALLMAN)/man1
 	cp dMagneticini.5 $(INSTALLMAN)/man5
-	cp README.txt $(INSTALLSHARE)/dMagnetic
-	cp LICENSE.txt $(INSTALLSHARE)/dMagnetic
+	#cp README.txt $(INSTALLSHARE)/dMagnetic
+	#cp LICENSE.txt $(INSTALLSHARE)/dMagnetic
 	cp dMagnetic.ini $(INSTALLSHARE)/dMagnetic
 
 

