Transform the BSD-style Makefile into Debian-style
--- a/Makefile	2022-04-28 15:26:27.496356679 +0200
+++ b/Makefile	2022-04-28 15:26:27.500356702 +0200
@@ -23,10 +23,10 @@
 #OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 #OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PREFIX?=/usr/local
-INSTALLBIN=$(PREFIX)/bin
-INSTALLSHARE=$(PREFIX)/share/games
-INSTALLMAN=$(PREFIX)/share/man
+DESTDIR?=/usr/local
+INSTALLBIN=$(DESTDIR)/bin
+INSTALLSHARE=$(DESTDIR)/share/games
+INSTALLMAN=$(DESTDIR)/share/man
 
 CC?=gcc
 AR?=ar
@@ -79,7 +79,7 @@
 OBJ_TOPLEVEL=${SOURCES_TOPLEVEL:.c=.o}
 
 all:	dMagnetic dMagnetic.ini
-#	strip dMagnetic
+#	#strip dMagnetic
 
 clean:
 	rm -rf dMagnetic dMagnetic.ini
@@ -98,8 +98,8 @@
 	cp dMagnetic $(INSTALLBIN)
 	cp dMagnetic.6 $(INSTALLMAN)/man6/
 	cp dMagneticini.5 $(INSTALLMAN)/man5/
-	cp README.txt $(INSTALLSHARE)/dMagnetic/
-	cp LICENSE.txt $(INSTALLSHARE)/dMagnetic/
+	#cp README.txt $(INSTALLSHARE)/dMagnetic/
+	#cp LICENSE.txt $(INSTALLSHARE)/dMagnetic/
 	cp dMagnetic.ini $(INSTALLSHARE)/dMagnetic/
 
 

